// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ActivePrice provides a mock function with given fields: categoryID
func (_m *MockRepository) ActivePrice(categoryID int) (string, float64, bool, error) {
	ret := _m.Called(categoryID)

	if len(ret) == 0 {
		panic("no return value specified for ActivePrice")
	}

	var r0 string
	var r1 float64
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(int) (string, float64, bool, error)); ok {
		return rf(categoryID)
	}
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(categoryID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int) float64); ok {
		r1 = rf(categoryID)
	} else {
		r1 = ret.Get(1).(float64)
	}

	if rf, ok := ret.Get(2).(func(int) bool); ok {
		r2 = rf(categoryID)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(int) error); ok {
		r3 = rf(categoryID)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockRepository_ActivePrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActivePrice'
type MockRepository_ActivePrice_Call struct {
	*mock.Call
}

// ActivePrice is a helper method to define mock.On call
//   - categoryID int
func (_e *MockRepository_Expecter) ActivePrice(categoryID interface{}) *MockRepository_ActivePrice_Call {
	return &MockRepository_ActivePrice_Call{Call: _e.mock.On("ActivePrice", categoryID)}
}

func (_c *MockRepository_ActivePrice_Call) Run(run func(categoryID int)) *MockRepository_ActivePrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_ActivePrice_Call) Return(categoryName string, pricePerUnit float64, found bool, err error) *MockRepository_ActivePrice_Call {
	_c.Call.Return(categoryName, pricePerUnit, found, err)
	return _c
}

func (_c *MockRepository_ActivePrice_Call) RunAndReturn(run func(int) (string, float64, bool, error)) *MockRepository_ActivePrice_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
