// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	report "github.com/fahmi0sd/waste-banks-and-donations/service/report"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// RoleAndLocation provides a mock function with given fields: userID
func (_m *MockRepository) RoleAndLocation(userID int) (string, *int, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for RoleAndLocation")
	}

	var r0 string
	var r1 *int
	var r2 error
	if rf, ok := ret.Get(0).(func(int) (string, *int, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int) *int); ok {
		r1 = rf(userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*int)
		}
	}

	if rf, ok := ret.Get(2).(func(int) error); ok {
		r2 = rf(userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_RoleAndLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RoleAndLocation'
type MockRepository_RoleAndLocation_Call struct {
	*mock.Call
}

// RoleAndLocation is a helper method to define mock.On call
//   - userID int
func (_e *MockRepository_Expecter) RoleAndLocation(userID interface{}) *MockRepository_RoleAndLocation_Call {
	return &MockRepository_RoleAndLocation_Call{Call: _e.mock.On("RoleAndLocation", userID)}
}

func (_c *MockRepository_RoleAndLocation_Call) Run(run func(userID int)) *MockRepository_RoleAndLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_RoleAndLocation_Call) Return(role string, locationID *int, err error) *MockRepository_RoleAndLocation_Call {
	_c.Call.Return(role, locationID, err)
	return _c
}

func (_c *MockRepository_RoleAndLocation_Call) RunAndReturn(run func(int) (string, *int, error)) *MockRepository_RoleAndLocation_Call {
	_c.Call.Return(run)
	return _c
}

// TransactionSummary provides a mock function with given fields: filter
func (_m *MockRepository) TransactionSummary(filter report.Filter) ([]report.TransactionSummary, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for TransactionSummary")
	}

	var r0 []report.TransactionSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(report.Filter) ([]report.TransactionSummary, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(report.Filter) []report.TransactionSummary); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]report.TransactionSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(report.Filter) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_TransactionSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransactionSummary'
type MockRepository_TransactionSummary_Call struct {
	*mock.Call
}

// TransactionSummary is a helper method to define mock.On call
//   - filter report.Filter
func (_e *MockRepository_Expecter) TransactionSummary(filter interface{}) *MockRepository_TransactionSummary_Call {
	return &MockRepository_TransactionSummary_Call{Call: _e.mock.On("TransactionSummary", filter)}
}

func (_c *MockRepository_TransactionSummary_Call) Run(run func(filter report.Filter)) *MockRepository_TransactionSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(report.Filter))
	})
	return _c
}

func (_c *MockRepository_TransactionSummary_Call) Return(_a0 []report.TransactionSummary, _a1 error) *MockRepository_TransactionSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_TransactionSummary_Call) RunAndReturn(run func(report.Filter) ([]report.TransactionSummary, error)) *MockRepository_TransactionSummary_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
