// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockMailer is an autogenerated mock type for the Mailer type
type MockMailer struct {
	mock.Mock
}

type MockMailer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMailer) EXPECT() *MockMailer_Expecter {
	return &MockMailer_Expecter{mock: &_m.Mock}
}

// SendEmail provides a mock function with given fields: toEmail, toName, subject, textContent
func (_m *MockMailer) SendEmail(toEmail string, toName string, subject string, textContent string) error {
	ret := _m.Called(toEmail, toName, subject, textContent)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = rf(toEmail, toName, subject, textContent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMailer_SendEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmail'
type MockMailer_SendEmail_Call struct {
	*mock.Call
}

// SendEmail is a helper method to define mock.On call
//   - toEmail string
//   - toName string
//   - subject string
//   - textContent string
func (_e *MockMailer_Expecter) SendEmail(toEmail interface{}, toName interface{}, subject interface{}, textContent interface{}) *MockMailer_SendEmail_Call {
	return &MockMailer_SendEmail_Call{Call: _e.mock.On("SendEmail", toEmail, toName, subject, textContent)}
}

func (_c *MockMailer_SendEmail_Call) Run(run func(toEmail string, toName string, subject string, textContent string)) *MockMailer_SendEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockMailer_SendEmail_Call) Return(_a0 error) *MockMailer_SendEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMailer_SendEmail_Call) RunAndReturn(run func(string, string, string, string) error) *MockMailer_SendEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMailer creates a new instance of MockMailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMailer {
	mock := &MockMailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
