// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	notification "github.com/fahmi0sd/waste-banks-and-donations/service/notification"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ListByUser provides a mock function with given fields: userID
func (_m *MockRepository) ListByUser(userID int) ([]notification.NotificationLog, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []notification.NotificationLog
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]notification.NotificationLog, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) []notification.NotificationLog); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]notification.NotificationLog)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - userID int
func (_e *MockRepository_Expecter) ListByUser(userID interface{}) *MockRepository_ListByUser_Call {
	return &MockRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", userID)}
}

func (_c *MockRepository_ListByUser_Call) Run(run func(userID int)) *MockRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_ListByUser_Call) Return(_a0 []notification.NotificationLog, _a1 error) *MockRepository_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListByUser_Call) RunAndReturn(run func(int) ([]notification.NotificationLog, error)) *MockRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Log provides a mock function with given fields: n
func (_m *MockRepository) Log(n notification.NotificationLog) error {
	ret := _m.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for Log")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(notification.NotificationLog) error); ok {
		r0 = rf(n)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type MockRepository_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//   - n notification.NotificationLog
func (_e *MockRepository_Expecter) Log(n interface{}) *MockRepository_Log_Call {
	return &MockRepository_Log_Call{Call: _e.mock.On("Log", n)}
}

func (_c *MockRepository_Log_Call) Run(run func(n notification.NotificationLog)) *MockRepository_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(notification.NotificationLog))
	})
	return _c
}

func (_c *MockRepository_Log_Call) Return(_a0 error) *MockRepository_Log_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Log_Call) RunAndReturn(run func(notification.NotificationLog) error) *MockRepository_Log_Call {
	_c.Call.Return(run)
	return _c
}

// UserContact provides a mock function with given fields: userID
func (_m *MockRepository) UserContact(userID int) (string, string, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for UserContact")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(int) (string, string, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int) string); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(int) error); ok {
		r2 = rf(userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_UserContact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserContact'
type MockRepository_UserContact_Call struct {
	*mock.Call
}

// UserContact is a helper method to define mock.On call
//   - userID int
func (_e *MockRepository_Expecter) UserContact(userID interface{}) *MockRepository_UserContact_Call {
	return &MockRepository_UserContact_Call{Call: _e.mock.On("UserContact", userID)}
}

func (_c *MockRepository_UserContact_Call) Run(run func(userID int)) *MockRepository_UserContact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_UserContact_Call) Return(name string, email string, err error) *MockRepository_UserContact_Call {
	_c.Call.Return(name, email, err)
	return _c
}

func (_c *MockRepository_UserContact_Call) RunAndReturn(run func(int) (string, string, error)) *MockRepository_UserContact_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
