with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: "mocks"
filename: "{{.InterfaceName}}.go"

packages:
  github.com/fahmi0sd/waste-banks-and-donations/service/auth:
    interfaces:
      Repository:
  github.com/fahmi0sd/waste-banks-and-donations/service/backup:
    interfaces:
      Repository:
  github.com/fahmi0sd/waste-banks-and-donations/service/calculator:
    interfaces:
      Repository:
  github.com/fahmi0sd/waste-banks-and-donations/service/campaign:
    interfaces:
      Repository:
      UpdateRepository:
      NotificationSender:
  github.com/fahmi0sd/waste-banks-and-donations/service/category:
    interfaces:
      Repository:
  github.com/fahmi0sd/waste-banks-and-donations/service/location:
    interfaces:
      Repository:
  github.com/fahmi0sd/waste-banks-and-donations/service/notification:
    interfaces:
      Repository:
      Mailer:
  github.com/fahmi0sd/waste-banks-and-donations/service/price:
    interfaces:
      Repository:
  github.com/fahmi0sd/waste-banks-and-donations/service/queue:
    interfaces:
      Repository:
  github.com/fahmi0sd/waste-banks-and-donations/service/report:
    interfaces:
      Repository:
  github.com/fahmi0sd/waste-banks-and-donations/service/user:
    interfaces:
      Repository:
  github.com/fahmi0sd/waste-banks-and-donations/service/wallet:
    interfaces:
      Repository:
  github.com/fahmi0sd/waste-banks-and-donations/service/waste-transaction:
    interfaces:
      Repository:
      NotificationSender: