// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	price "github.com/fahmi0sd/waste-banks-and-donations/service/price"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ActivePrice provides a mock function with given fields: categoryID
func (_m *MockRepository) ActivePrice(categoryID int) (price.Price, bool, error) {
	ret := _m.Called(categoryID)

	if len(ret) == 0 {
		panic("no return value specified for ActivePrice")
	}

	var r0 price.Price
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(int) (price.Price, bool, error)); ok {
		return rf(categoryID)
	}
	if rf, ok := ret.Get(0).(func(int) price.Price); ok {
		r0 = rf(categoryID)
	} else {
		r0 = ret.Get(0).(price.Price)
	}

	if rf, ok := ret.Get(1).(func(int) bool); ok {
		r1 = rf(categoryID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(int) error); ok {
		r2 = rf(categoryID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_ActivePrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActivePrice'
type MockRepository_ActivePrice_Call struct {
	*mock.Call
}

// ActivePrice is a helper method to define mock.On call
//   - categoryID int
func (_e *MockRepository_Expecter) ActivePrice(categoryID interface{}) *MockRepository_ActivePrice_Call {
	return &MockRepository_ActivePrice_Call{Call: _e.mock.On("ActivePrice", categoryID)}
}

func (_c *MockRepository_ActivePrice_Call) Run(run func(categoryID int)) *MockRepository_ActivePrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_ActivePrice_Call) Return(_a0 price.Price, _a1 bool, _a2 error) *MockRepository_ActivePrice_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepository_ActivePrice_Call) RunAndReturn(run func(int) (price.Price, bool, error)) *MockRepository_ActivePrice_Call {
	_c.Call.Return(run)
	return _c
}

// CategoryExists provides a mock function with given fields: categoryID
func (_m *MockRepository) CategoryExists(categoryID int) (bool, error) {
	ret := _m.Called(categoryID)

	if len(ret) == 0 {
		panic("no return value specified for CategoryExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (bool, error)); ok {
		return rf(categoryID)
	}
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(categoryID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(categoryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CategoryExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CategoryExists'
type MockRepository_CategoryExists_Call struct {
	*mock.Call
}

// CategoryExists is a helper method to define mock.On call
//   - categoryID int
func (_e *MockRepository_Expecter) CategoryExists(categoryID interface{}) *MockRepository_CategoryExists_Call {
	return &MockRepository_CategoryExists_Call{Call: _e.mock.On("CategoryExists", categoryID)}
}

func (_c *MockRepository_CategoryExists_Call) Run(run func(categoryID int)) *MockRepository_CategoryExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_CategoryExists_Call) Return(_a0 bool, _a1 error) *MockRepository_CategoryExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CategoryExists_Call) RunAndReturn(run func(int) (bool, error)) *MockRepository_CategoryExists_Call {
	_c.Call.Return(run)
	return _c
}

// CloseActivePrice provides a mock function with given fields: categoryID
func (_m *MockRepository) CloseActivePrice(categoryID int) error {
	ret := _m.Called(categoryID)

	if len(ret) == 0 {
		panic("no return value specified for CloseActivePrice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(categoryID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CloseActivePrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseActivePrice'
type MockRepository_CloseActivePrice_Call struct {
	*mock.Call
}

// CloseActivePrice is a helper method to define mock.On call
//   - categoryID int
func (_e *MockRepository_Expecter) CloseActivePrice(categoryID interface{}) *MockRepository_CloseActivePrice_Call {
	return &MockRepository_CloseActivePrice_Call{Call: _e.mock.On("CloseActivePrice", categoryID)}
}

func (_c *MockRepository_CloseActivePrice_Call) Run(run func(categoryID int)) *MockRepository_CloseActivePrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_CloseActivePrice_Call) Return(_a0 error) *MockRepository_CloseActivePrice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CloseActivePrice_Call) RunAndReturn(run func(int) error) *MockRepository_CloseActivePrice_Call {
	_c.Call.Return(run)
	return _c
}

// History provides a mock function with given fields: categoryID
func (_m *MockRepository) History(categoryID int) ([]price.Price, error) {
	ret := _m.Called(categoryID)

	if len(ret) == 0 {
		panic("no return value specified for History")
	}

	var r0 []price.Price
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]price.Price, error)); ok {
		return rf(categoryID)
	}
	if rf, ok := ret.Get(0).(func(int) []price.Price); ok {
		r0 = rf(categoryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]price.Price)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(categoryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_History_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'History'
type MockRepository_History_Call struct {
	*mock.Call
}

// History is a helper method to define mock.On call
//   - categoryID int
func (_e *MockRepository_Expecter) History(categoryID interface{}) *MockRepository_History_Call {
	return &MockRepository_History_Call{Call: _e.mock.On("History", categoryID)}
}

func (_c *MockRepository_History_Call) Run(run func(categoryID int)) *MockRepository_History_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_History_Call) Return(_a0 []price.Price, _a1 error) *MockRepository_History_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_History_Call) RunAndReturn(run func(int) ([]price.Price, error)) *MockRepository_History_Call {
	_c.Call.Return(run)
	return _c
}

// InsertPrice provides a mock function with given fields: categoryID, pricePerUnit, setBy
func (_m *MockRepository) InsertPrice(categoryID int, pricePerUnit float64, setBy int) (price.Price, error) {
	ret := _m.Called(categoryID, pricePerUnit, setBy)

	if len(ret) == 0 {
		panic("no return value specified for InsertPrice")
	}

	var r0 price.Price
	var r1 error
	if rf, ok := ret.Get(0).(func(int, float64, int) (price.Price, error)); ok {
		return rf(categoryID, pricePerUnit, setBy)
	}
	if rf, ok := ret.Get(0).(func(int, float64, int) price.Price); ok {
		r0 = rf(categoryID, pricePerUnit, setBy)
	} else {
		r0 = ret.Get(0).(price.Price)
	}

	if rf, ok := ret.Get(1).(func(int, float64, int) error); ok {
		r1 = rf(categoryID, pricePerUnit, setBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_InsertPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertPrice'
type MockRepository_InsertPrice_Call struct {
	*mock.Call
}

// InsertPrice is a helper method to define mock.On call
//   - categoryID int
//   - pricePerUnit float64
//   - setBy int
func (_e *MockRepository_Expecter) InsertPrice(categoryID interface{}, pricePerUnit interface{}, setBy interface{}) *MockRepository_InsertPrice_Call {
	return &MockRepository_InsertPrice_Call{Call: _e.mock.On("InsertPrice", categoryID, pricePerUnit, setBy)}
}

func (_c *MockRepository_InsertPrice_Call) Run(run func(categoryID int, pricePerUnit float64, setBy int)) *MockRepository_InsertPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(float64), args[2].(int))
	})
	return _c
}

func (_c *MockRepository_InsertPrice_Call) Return(_a0 price.Price, _a1 error) *MockRepository_InsertPrice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_InsertPrice_Call) RunAndReturn(run func(int, float64, int) (price.Price, error)) *MockRepository_InsertPrice_Call {
	_c.Call.Return(run)
	return _c
}

// RoleOf provides a mock function with given fields: userID
func (_m *MockRepository) RoleOf(userID int) (string, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for RoleOf")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (string, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_RoleOf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RoleOf'
type MockRepository_RoleOf_Call struct {
	*mock.Call
}

// RoleOf is a helper method to define mock.On call
//   - userID int
func (_e *MockRepository_Expecter) RoleOf(userID interface{}) *MockRepository_RoleOf_Call {
	return &MockRepository_RoleOf_Call{Call: _e.mock.On("RoleOf", userID)}
}

func (_c *MockRepository_RoleOf_Call) Run(run func(userID int)) *MockRepository_RoleOf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_RoleOf_Call) Return(_a0 string, _a1 error) *MockRepository_RoleOf_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_RoleOf_Call) RunAndReturn(run func(int) (string, error)) *MockRepository_RoleOf_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
