// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	auth "github.com/fahmi0sd/waste-banks-and-donations/service/auth"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: name, email, phone, passwordHash
func (_m *MockRepository) Create(name string, email string, phone string, passwordHash string) (auth.UserRecord, error) {
	ret := _m.Called(name, email, phone, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 auth.UserRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) (auth.UserRecord, error)); ok {
		return rf(name, email, phone, passwordHash)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string) auth.UserRecord); ok {
		r0 = rf(name, email, phone, passwordHash)
	} else {
		r0 = ret.Get(0).(auth.UserRecord)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string) error); ok {
		r1 = rf(name, email, phone, passwordHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - name string
//   - email string
//   - phone string
//   - passwordHash string
func (_e *MockRepository_Expecter) Create(name interface{}, email interface{}, phone interface{}, passwordHash interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", name, email, phone, passwordHash)}
}

func (_c *MockRepository_Create_Call) Run(run func(name string, email string, phone string, passwordHash string)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 auth.UserRecord, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(string, string, string, string) (auth.UserRecord, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// EmailExists provides a mock function with given fields: email
func (_m *MockRepository) EmailExists(email string) (bool, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for EmailExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_EmailExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmailExists'
type MockRepository_EmailExists_Call struct {
	*mock.Call
}

// EmailExists is a helper method to define mock.On call
//   - email string
func (_e *MockRepository_Expecter) EmailExists(email interface{}) *MockRepository_EmailExists_Call {
	return &MockRepository_EmailExists_Call{Call: _e.mock.On("EmailExists", email)}
}

func (_c *MockRepository_EmailExists_Call) Run(run func(email string)) *MockRepository_EmailExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRepository_EmailExists_Call) Return(_a0 bool, _a1 error) *MockRepository_EmailExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_EmailExists_Call) RunAndReturn(run func(string) (bool, error)) *MockRepository_EmailExists_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function with given fields: email
func (_m *MockRepository) FindByEmail(email string) (auth.UserRecord, bool, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 auth.UserRecord
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (auth.UserRecord, bool, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) auth.UserRecord); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(auth.UserRecord)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(email)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockRepository_Expecter) FindByEmail(email interface{}) *MockRepository_FindByEmail_Call {
	return &MockRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", email)}
}

func (_c *MockRepository_FindByEmail_Call) Run(run func(email string)) *MockRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRepository_FindByEmail_Call) Return(_a0 auth.UserRecord, _a1 bool, _a2 error) *MockRepository_FindByEmail_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepository_FindByEmail_Call) RunAndReturn(run func(string) (auth.UserRecord, bool, error)) *MockRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
