// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockNotificationSender is an autogenerated mock type for the NotificationSender type
type MockNotificationSender struct {
	mock.Mock
}

type MockNotificationSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationSender) EXPECT() *MockNotificationSender_Expecter {
	return &MockNotificationSender_Expecter{mock: &_m.Mock}
}

// NotifyDepositUpdate provides a mock function with given fields: userID, amount
func (_m *MockNotificationSender) NotifyDepositUpdate(userID int, amount float64) error {
	ret := _m.Called(userID, amount)

	if len(ret) == 0 {
		panic("no return value specified for NotifyDepositUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, float64) error); ok {
		r0 = rf(userID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationSender_NotifyDepositUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyDepositUpdate'
type MockNotificationSender_NotifyDepositUpdate_Call struct {
	*mock.Call
}

// NotifyDepositUpdate is a helper method to define mock.On call
//   - userID int
//   - amount float64
func (_e *MockNotificationSender_Expecter) NotifyDepositUpdate(userID interface{}, amount interface{}) *MockNotificationSender_NotifyDepositUpdate_Call {
	return &MockNotificationSender_NotifyDepositUpdate_Call{Call: _e.mock.On("NotifyDepositUpdate", userID, amount)}
}

func (_c *MockNotificationSender_NotifyDepositUpdate_Call) Run(run func(userID int, amount float64)) *MockNotificationSender_NotifyDepositUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(float64))
	})
	return _c
}

func (_c *MockNotificationSender_NotifyDepositUpdate_Call) Return(_a0 error) *MockNotificationSender_NotifyDepositUpdate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationSender_NotifyDepositUpdate_Call) RunAndReturn(run func(int, float64) error) *MockNotificationSender_NotifyDepositUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationSender creates a new instance of MockNotificationSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationSender {
	mock := &MockNotificationSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
