// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	wastetransaction "github.com/fahmi0sd/waste-banks-and-donations/service/waste-transaction"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CancelWithEffects provides a mock function with given fields: transactionID
func (_m *MockRepository) CancelWithEffects(transactionID int) (wastetransaction.WasteTransaction, error) {
	ret := _m.Called(transactionID)

	if len(ret) == 0 {
		panic("no return value specified for CancelWithEffects")
	}

	var r0 wastetransaction.WasteTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (wastetransaction.WasteTransaction, error)); ok {
		return rf(transactionID)
	}
	if rf, ok := ret.Get(0).(func(int) wastetransaction.WasteTransaction); ok {
		r0 = rf(transactionID)
	} else {
		r0 = ret.Get(0).(wastetransaction.WasteTransaction)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(transactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CancelWithEffects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelWithEffects'
type MockRepository_CancelWithEffects_Call struct {
	*mock.Call
}

// CancelWithEffects is a helper method to define mock.On call
//   - transactionID int
func (_e *MockRepository_Expecter) CancelWithEffects(transactionID interface{}) *MockRepository_CancelWithEffects_Call {
	return &MockRepository_CancelWithEffects_Call{Call: _e.mock.On("CancelWithEffects", transactionID)}
}

func (_c *MockRepository_CancelWithEffects_Call) Run(run func(transactionID int)) *MockRepository_CancelWithEffects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_CancelWithEffects_Call) Return(_a0 wastetransaction.WasteTransaction, _a1 error) *MockRepository_CancelWithEffects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CancelWithEffects_Call) RunAndReturn(run func(int) (wastetransaction.WasteTransaction, error)) *MockRepository_CancelWithEffects_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithEffects provides a mock function with given fields: input
func (_m *MockRepository) CreateWithEffects(input wastetransaction.CreateInput) (wastetransaction.WasteTransaction, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithEffects")
	}

	var r0 wastetransaction.WasteTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(wastetransaction.CreateInput) (wastetransaction.WasteTransaction, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(wastetransaction.CreateInput) wastetransaction.WasteTransaction); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(wastetransaction.WasteTransaction)
	}

	if rf, ok := ret.Get(1).(func(wastetransaction.CreateInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateWithEffects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithEffects'
type MockRepository_CreateWithEffects_Call struct {
	*mock.Call
}

// CreateWithEffects is a helper method to define mock.On call
//   - input wastetransaction.CreateInput
func (_e *MockRepository_Expecter) CreateWithEffects(input interface{}) *MockRepository_CreateWithEffects_Call {
	return &MockRepository_CreateWithEffects_Call{Call: _e.mock.On("CreateWithEffects", input)}
}

func (_c *MockRepository_CreateWithEffects_Call) Run(run func(input wastetransaction.CreateInput)) *MockRepository_CreateWithEffects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(wastetransaction.CreateInput))
	})
	return _c
}

func (_c *MockRepository_CreateWithEffects_Call) Return(_a0 wastetransaction.WasteTransaction, _a1 error) *MockRepository_CreateWithEffects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateWithEffects_Call) RunAndReturn(run func(wastetransaction.CreateInput) (wastetransaction.WasteTransaction, error)) *MockRepository_CreateWithEffects_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockRepository) GetByID(id int) (wastetransaction.WasteTransaction, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 wastetransaction.WasteTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (wastetransaction.WasteTransaction, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) wastetransaction.WasteTransaction); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(wastetransaction.WasteTransaction)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int
func (_e *MockRepository_Expecter) GetByID(id interface{}) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(id int)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(_a0 wastetransaction.WasteTransaction, _a1 error) *MockRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(int) (wastetransaction.WasteTransaction, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetDetailsByTransactionID provides a mock function with given fields: transactionID
func (_m *MockRepository) GetDetailsByTransactionID(transactionID int) ([]wastetransaction.WasteTransactionDetail, error) {
	ret := _m.Called(transactionID)

	if len(ret) == 0 {
		panic("no return value specified for GetDetailsByTransactionID")
	}

	var r0 []wastetransaction.WasteTransactionDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]wastetransaction.WasteTransactionDetail, error)); ok {
		return rf(transactionID)
	}
	if rf, ok := ret.Get(0).(func(int) []wastetransaction.WasteTransactionDetail); ok {
		r0 = rf(transactionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]wastetransaction.WasteTransactionDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(transactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetDetailsByTransactionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDetailsByTransactionID'
type MockRepository_GetDetailsByTransactionID_Call struct {
	*mock.Call
}

// GetDetailsByTransactionID is a helper method to define mock.On call
//   - transactionID int
func (_e *MockRepository_Expecter) GetDetailsByTransactionID(transactionID interface{}) *MockRepository_GetDetailsByTransactionID_Call {
	return &MockRepository_GetDetailsByTransactionID_Call{Call: _e.mock.On("GetDetailsByTransactionID", transactionID)}
}

func (_c *MockRepository_GetDetailsByTransactionID_Call) Run(run func(transactionID int)) *MockRepository_GetDetailsByTransactionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_GetDetailsByTransactionID_Call) Return(_a0 []wastetransaction.WasteTransactionDetail, _a1 error) *MockRepository_GetDetailsByTransactionID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetDetailsByTransactionID_Call) RunAndReturn(run func(int) ([]wastetransaction.WasteTransactionDetail, error)) *MockRepository_GetDetailsByTransactionID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByLocation provides a mock function with given fields: locationID
func (_m *MockRepository) ListByLocation(locationID int) ([]wastetransaction.WasteTransaction, error) {
	ret := _m.Called(locationID)

	if len(ret) == 0 {
		panic("no return value specified for ListByLocation")
	}

	var r0 []wastetransaction.WasteTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]wastetransaction.WasteTransaction, error)); ok {
		return rf(locationID)
	}
	if rf, ok := ret.Get(0).(func(int) []wastetransaction.WasteTransaction); ok {
		r0 = rf(locationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]wastetransaction.WasteTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(locationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListByLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByLocation'
type MockRepository_ListByLocation_Call struct {
	*mock.Call
}

// ListByLocation is a helper method to define mock.On call
//   - locationID int
func (_e *MockRepository_Expecter) ListByLocation(locationID interface{}) *MockRepository_ListByLocation_Call {
	return &MockRepository_ListByLocation_Call{Call: _e.mock.On("ListByLocation", locationID)}
}

func (_c *MockRepository_ListByLocation_Call) Run(run func(locationID int)) *MockRepository_ListByLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_ListByLocation_Call) Return(_a0 []wastetransaction.WasteTransaction, _a1 error) *MockRepository_ListByLocation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListByLocation_Call) RunAndReturn(run func(int) ([]wastetransaction.WasteTransaction, error)) *MockRepository_ListByLocation_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: userID
func (_m *MockRepository) ListByUser(userID int) ([]wastetransaction.WasteTransaction, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []wastetransaction.WasteTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]wastetransaction.WasteTransaction, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) []wastetransaction.WasteTransaction); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]wastetransaction.WasteTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - userID int
func (_e *MockRepository_Expecter) ListByUser(userID interface{}) *MockRepository_ListByUser_Call {
	return &MockRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", userID)}
}

func (_c *MockRepository_ListByUser_Call) Run(run func(userID int)) *MockRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_ListByUser_Call) Return(_a0 []wastetransaction.WasteTransaction, _a1 error) *MockRepository_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListByUser_Call) RunAndReturn(run func(int) ([]wastetransaction.WasteTransaction, error)) *MockRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// QueueInfo provides a mock function with given fields: queueID
func (_m *MockRepository) QueueInfo(queueID int) (wastetransaction.QueueInfo, error) {
	ret := _m.Called(queueID)

	if len(ret) == 0 {
		panic("no return value specified for QueueInfo")
	}

	var r0 wastetransaction.QueueInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (wastetransaction.QueueInfo, error)); ok {
		return rf(queueID)
	}
	if rf, ok := ret.Get(0).(func(int) wastetransaction.QueueInfo); ok {
		r0 = rf(queueID)
	} else {
		r0 = ret.Get(0).(wastetransaction.QueueInfo)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(queueID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_QueueInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueueInfo'
type MockRepository_QueueInfo_Call struct {
	*mock.Call
}

// QueueInfo is a helper method to define mock.On call
//   - queueID int
func (_e *MockRepository_Expecter) QueueInfo(queueID interface{}) *MockRepository_QueueInfo_Call {
	return &MockRepository_QueueInfo_Call{Call: _e.mock.On("QueueInfo", queueID)}
}

func (_c *MockRepository_QueueInfo_Call) Run(run func(queueID int)) *MockRepository_QueueInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_QueueInfo_Call) Return(_a0 wastetransaction.QueueInfo, _a1 error) *MockRepository_QueueInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_QueueInfo_Call) RunAndReturn(run func(int) (wastetransaction.QueueInfo, error)) *MockRepository_QueueInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
