// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	user "github.com/fahmi0sd/waste-banks-and-donations/service/user"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function with given fields: name, email, phone, passwordHash, role, locationID
func (_m *MockRepository) CreateAccount(name string, email string, phone string, passwordHash string, role string, locationID *int) (user.Profile, error) {
	ret := _m.Called(name, email, phone, passwordHash, role, locationID)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 user.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, *int) (user.Profile, error)); ok {
		return rf(name, email, phone, passwordHash, role, locationID)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, *int) user.Profile); ok {
		r0 = rf(name, email, phone, passwordHash, role, locationID)
	} else {
		r0 = ret.Get(0).(user.Profile)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string, string, *int) error); ok {
		r1 = rf(name, email, phone, passwordHash, role, locationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type MockRepository_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - name string
//   - email string
//   - phone string
//   - passwordHash string
//   - role string
//   - locationID *int
func (_e *MockRepository_Expecter) CreateAccount(name interface{}, email interface{}, phone interface{}, passwordHash interface{}, role interface{}, locationID interface{}) *MockRepository_CreateAccount_Call {
	return &MockRepository_CreateAccount_Call{Call: _e.mock.On("CreateAccount", name, email, phone, passwordHash, role, locationID)}
}

func (_c *MockRepository_CreateAccount_Call) Run(run func(name string, email string, phone string, passwordHash string, role string, locationID *int)) *MockRepository_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(*int))
	})
	return _c
}

func (_c *MockRepository_CreateAccount_Call) Return(_a0 user.Profile, _a1 error) *MockRepository_CreateAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateAccount_Call) RunAndReturn(run func(string, string, string, string, string, *int) (user.Profile, error)) *MockRepository_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccount provides a mock function with given fields: id
func (_m *MockRepository) DeleteAccount(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type MockRepository_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - id int
func (_e *MockRepository_Expecter) DeleteAccount(id interface{}) *MockRepository_DeleteAccount_Call {
	return &MockRepository_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", id)}
}

func (_c *MockRepository_DeleteAccount_Call) Run(run func(id int)) *MockRepository_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_DeleteAccount_Call) Return(_a0 error) *MockRepository_DeleteAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteAccount_Call) RunAndReturn(run func(int) error) *MockRepository_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// EmailExists provides a mock function with given fields: email
func (_m *MockRepository) EmailExists(email string) (bool, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for EmailExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_EmailExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmailExists'
type MockRepository_EmailExists_Call struct {
	*mock.Call
}

// EmailExists is a helper method to define mock.On call
//   - email string
func (_e *MockRepository_Expecter) EmailExists(email interface{}) *MockRepository_EmailExists_Call {
	return &MockRepository_EmailExists_Call{Call: _e.mock.On("EmailExists", email)}
}

func (_c *MockRepository_EmailExists_Call) Run(run func(email string)) *MockRepository_EmailExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRepository_EmailExists_Call) Return(_a0 bool, _a1 error) *MockRepository_EmailExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_EmailExists_Call) RunAndReturn(run func(string) (bool, error)) *MockRepository_EmailExists_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockRepository) FindByID(id int) (user.Profile, bool, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 user.Profile
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(int) (user.Profile, bool, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) user.Profile); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(user.Profile)
	}

	if rf, ok := ret.Get(1).(func(int) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(int) error); ok {
		r2 = rf(id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id int
func (_e *MockRepository_Expecter) FindByID(id interface{}) *MockRepository_FindByID_Call {
	return &MockRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockRepository_FindByID_Call) Run(run func(id int)) *MockRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_FindByID_Call) Return(_a0 user.Profile, _a1 bool, _a2 error) *MockRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepository_FindByID_Call) RunAndReturn(run func(int) (user.Profile, bool, error)) *MockRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccounts provides a mock function with no fields
func (_m *MockRepository) ListAccounts() ([]user.Profile, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListAccounts")
	}

	var r0 []user.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]user.Profile, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []user.Profile); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccounts'
type MockRepository_ListAccounts_Call struct {
	*mock.Call
}

// ListAccounts is a helper method to define mock.On call
func (_e *MockRepository_Expecter) ListAccounts() *MockRepository_ListAccounts_Call {
	return &MockRepository_ListAccounts_Call{Call: _e.mock.On("ListAccounts")}
}

func (_c *MockRepository_ListAccounts_Call) Run(run func()) *MockRepository_ListAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_ListAccounts_Call) Return(_a0 []user.Profile, _a1 error) *MockRepository_ListAccounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListAccounts_Call) RunAndReturn(run func() ([]user.Profile, error)) *MockRepository_ListAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// RoleOf provides a mock function with given fields: userID
func (_m *MockRepository) RoleOf(userID int) (string, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for RoleOf")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (string, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_RoleOf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RoleOf'
type MockRepository_RoleOf_Call struct {
	*mock.Call
}

// RoleOf is a helper method to define mock.On call
//   - userID int
func (_e *MockRepository_Expecter) RoleOf(userID interface{}) *MockRepository_RoleOf_Call {
	return &MockRepository_RoleOf_Call{Call: _e.mock.On("RoleOf", userID)}
}

func (_c *MockRepository_RoleOf_Call) Run(run func(userID int)) *MockRepository_RoleOf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_RoleOf_Call) Return(_a0 string, _a1 error) *MockRepository_RoleOf_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_RoleOf_Call) RunAndReturn(run func(int) (string, error)) *MockRepository_RoleOf_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccount provides a mock function with given fields: id, name, phone, role, locationID
func (_m *MockRepository) UpdateAccount(id int, name *string, phone *string, role *string, locationID *int) error {
	ret := _m.Called(id, name, phone, role, locationID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, *string, *string, *string, *int) error); ok {
		r0 = rf(id, name, phone, role, locationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccount'
type MockRepository_UpdateAccount_Call struct {
	*mock.Call
}

// UpdateAccount is a helper method to define mock.On call
//   - id int
//   - name *string
//   - phone *string
//   - role *string
//   - locationID *int
func (_e *MockRepository_Expecter) UpdateAccount(id interface{}, name interface{}, phone interface{}, role interface{}, locationID interface{}) *MockRepository_UpdateAccount_Call {
	return &MockRepository_UpdateAccount_Call{Call: _e.mock.On("UpdateAccount", id, name, phone, role, locationID)}
}

func (_c *MockRepository_UpdateAccount_Call) Run(run func(id int, name *string, phone *string, role *string, locationID *int)) *MockRepository_UpdateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(*string), args[2].(*string), args[3].(*string), args[4].(*int))
	})
	return _c
}

func (_c *MockRepository_UpdateAccount_Call) Return(_a0 error) *MockRepository_UpdateAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateAccount_Call) RunAndReturn(run func(int, *string, *string, *string, *int) error) *MockRepository_UpdateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: id, name, phone
func (_m *MockRepository) UpdateProfile(id int, name *string, phone *string) error {
	ret := _m.Called(id, name, phone)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, *string, *string) error); ok {
		r0 = rf(id, name, phone)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockRepository_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - id int
//   - name *string
//   - phone *string
func (_e *MockRepository_Expecter) UpdateProfile(id interface{}, name interface{}, phone interface{}) *MockRepository_UpdateProfile_Call {
	return &MockRepository_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", id, name, phone)}
}

func (_c *MockRepository_UpdateProfile_Call) Run(run func(id int, name *string, phone *string)) *MockRepository_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(*string), args[2].(*string))
	})
	return _c
}

func (_c *MockRepository_UpdateProfile_Call) Return(_a0 error) *MockRepository_UpdateProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateProfile_Call) RunAndReturn(run func(int, *string, *string) error) *MockRepository_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
