// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	category "github.com/fahmi0sd/waste-banks-and-donations/service/category"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: c
func (_m *MockRepository) Create(c category.Category) (category.Category, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 category.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(category.Category) (category.Category, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(category.Category) category.Category); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(category.Category)
	}

	if rf, ok := ret.Get(1).(func(category.Category) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - c category.Category
func (_e *MockRepository_Expecter) Create(c interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", c)}
}

func (_c *MockRepository_Create_Call) Run(run func(c category.Category)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(category.Category))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 category.Category, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(category.Category) (category.Category, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockRepository) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int
func (_e *MockRepository_Expecter) Delete(id interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(id int)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(_a0 error) *MockRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(int) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockRepository) GetByID(id int) (category.Category, bool, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 category.Category
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(int) (category.Category, bool, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) category.Category); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(category.Category)
	}

	if rf, ok := ret.Get(1).(func(int) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(int) error); ok {
		r2 = rf(id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int
func (_e *MockRepository_Expecter) GetByID(id interface{}) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(id int)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(_a0 category.Category, _a1 bool, _a2 error) *MockRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(int) (category.Category, bool, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with no fields
func (_m *MockRepository) List() ([]category.Category, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []category.Category
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]category.Category, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []category.Category); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]category.Category)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockRepository_Expecter) List() *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockRepository_List_Call) Run(run func()) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(_a0 []category.Category, _a1 error) *MockRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func() ([]category.Category, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// RoleOf provides a mock function with given fields: userID
func (_m *MockRepository) RoleOf(userID int) (string, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for RoleOf")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (string, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_RoleOf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RoleOf'
type MockRepository_RoleOf_Call struct {
	*mock.Call
}

// RoleOf is a helper method to define mock.On call
//   - userID int
func (_e *MockRepository_Expecter) RoleOf(userID interface{}) *MockRepository_RoleOf_Call {
	return &MockRepository_RoleOf_Call{Call: _e.mock.On("RoleOf", userID)}
}

func (_c *MockRepository_RoleOf_Call) Run(run func(userID int)) *MockRepository_RoleOf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_RoleOf_Call) Return(_a0 string, _a1 error) *MockRepository_RoleOf_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_RoleOf_Call) RunAndReturn(run func(int) (string, error)) *MockRepository_RoleOf_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: id, name, parentCategoryID, unit, isActive
func (_m *MockRepository) Update(id int, name *string, parentCategoryID *int, unit *string, isActive *bool) error {
	ret := _m.Called(id, name, parentCategoryID, unit, isActive)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, *string, *int, *string, *bool) error); ok {
		r0 = rf(id, name, parentCategoryID, unit, isActive)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id int
//   - name *string
//   - parentCategoryID *int
//   - unit *string
//   - isActive *bool
func (_e *MockRepository_Expecter) Update(id interface{}, name interface{}, parentCategoryID interface{}, unit interface{}, isActive interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", id, name, parentCategoryID, unit, isActive)}
}

func (_c *MockRepository_Update_Call) Run(run func(id int, name *string, parentCategoryID *int, unit *string, isActive *bool)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(*string), args[2].(*int), args[3].(*string), args[4].(*bool))
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(_a0 error) *MockRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(int, *string, *int, *string, *bool) error) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
