// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockNotificationSender is an autogenerated mock type for the NotificationSender type
type MockNotificationSender struct {
	mock.Mock
}

type MockNotificationSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationSender) EXPECT() *MockNotificationSender_Expecter {
	return &MockNotificationSender_Expecter{mock: &_m.Mock}
}

// NotifyDonationUpdate provides a mock function with given fields: userID, campaignTitle, updateContent
func (_m *MockNotificationSender) NotifyDonationUpdate(userID int, campaignTitle string, updateContent string) error {
	ret := _m.Called(userID, campaignTitle, updateContent)

	if len(ret) == 0 {
		panic("no return value specified for NotifyDonationUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string, string) error); ok {
		r0 = rf(userID, campaignTitle, updateContent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationSender_NotifyDonationUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyDonationUpdate'
type MockNotificationSender_NotifyDonationUpdate_Call struct {
	*mock.Call
}

// NotifyDonationUpdate is a helper method to define mock.On call
//   - userID int
//   - campaignTitle string
//   - updateContent string
func (_e *MockNotificationSender_Expecter) NotifyDonationUpdate(userID interface{}, campaignTitle interface{}, updateContent interface{}) *MockNotificationSender_NotifyDonationUpdate_Call {
	return &MockNotificationSender_NotifyDonationUpdate_Call{Call: _e.mock.On("NotifyDonationUpdate", userID, campaignTitle, updateContent)}
}

func (_c *MockNotificationSender_NotifyDonationUpdate_Call) Run(run func(userID int, campaignTitle string, updateContent string)) *MockNotificationSender_NotifyDonationUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockNotificationSender_NotifyDonationUpdate_Call) Return(_a0 error) *MockNotificationSender_NotifyDonationUpdate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationSender_NotifyDonationUpdate_Call) RunAndReturn(run func(int, string, string) error) *MockNotificationSender_NotifyDonationUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationSender creates a new instance of MockNotificationSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationSender {
	mock := &MockNotificationSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
