// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	campaign "github.com/fahmi0sd/waste-banks-and-donations/service/campaign"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	wallet "github.com/fahmi0sd/waste-banks-and-donations/service/wallet"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: c
func (_m *MockRepository) Create(c campaign.Campaign) (campaign.Campaign, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 campaign.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(campaign.Campaign) (campaign.Campaign, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(campaign.Campaign) campaign.Campaign); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(campaign.Campaign)
	}

	if rf, ok := ret.Get(1).(func(campaign.Campaign) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - c campaign.Campaign
func (_e *MockRepository_Expecter) Create(c interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", c)}
}

func (_c *MockRepository_Create_Call) Run(run func(c campaign.Campaign)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(campaign.Campaign))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 campaign.Campaign, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(campaign.Campaign) (campaign.Campaign, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDonation provides a mock function with given fields: tx, donation
func (_m *MockRepository) CreateDonation(tx *gorm.DB, donation campaign.Donation) (campaign.Donation, error) {
	ret := _m.Called(tx, donation)

	if len(ret) == 0 {
		panic("no return value specified for CreateDonation")
	}

	var r0 campaign.Donation
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, campaign.Donation) (campaign.Donation, error)); ok {
		return rf(tx, donation)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, campaign.Donation) campaign.Donation); ok {
		r0 = rf(tx, donation)
	} else {
		r0 = ret.Get(0).(campaign.Donation)
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, campaign.Donation) error); ok {
		r1 = rf(tx, donation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateDonation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDonation'
type MockRepository_CreateDonation_Call struct {
	*mock.Call
}

// CreateDonation is a helper method to define mock.On call
//   - tx *gorm.DB
//   - donation campaign.Donation
func (_e *MockRepository_Expecter) CreateDonation(tx interface{}, donation interface{}) *MockRepository_CreateDonation_Call {
	return &MockRepository_CreateDonation_Call{Call: _e.mock.On("CreateDonation", tx, donation)}
}

func (_c *MockRepository_CreateDonation_Call) Run(run func(tx *gorm.DB, donation campaign.Donation)) *MockRepository_CreateDonation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(campaign.Donation))
	})
	return _c
}

func (_c *MockRepository_CreateDonation_Call) Return(_a0 campaign.Donation, _a1 error) *MockRepository_CreateDonation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateDonation_Call) RunAndReturn(run func(*gorm.DB, campaign.Donation) (campaign.Donation, error)) *MockRepository_CreateDonation_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUpdate provides a mock function with given fields: update
func (_m *MockRepository) CreateUpdate(update campaign.CampaignUpdate) (campaign.CampaignUpdate, error) {
	ret := _m.Called(update)

	if len(ret) == 0 {
		panic("no return value specified for CreateUpdate")
	}

	var r0 campaign.CampaignUpdate
	var r1 error
	if rf, ok := ret.Get(0).(func(campaign.CampaignUpdate) (campaign.CampaignUpdate, error)); ok {
		return rf(update)
	}
	if rf, ok := ret.Get(0).(func(campaign.CampaignUpdate) campaign.CampaignUpdate); ok {
		r0 = rf(update)
	} else {
		r0 = ret.Get(0).(campaign.CampaignUpdate)
	}

	if rf, ok := ret.Get(1).(func(campaign.CampaignUpdate) error); ok {
		r1 = rf(update)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUpdate'
type MockRepository_CreateUpdate_Call struct {
	*mock.Call
}

// CreateUpdate is a helper method to define mock.On call
//   - update campaign.CampaignUpdate
func (_e *MockRepository_Expecter) CreateUpdate(update interface{}) *MockRepository_CreateUpdate_Call {
	return &MockRepository_CreateUpdate_Call{Call: _e.mock.On("CreateUpdate", update)}
}

func (_c *MockRepository_CreateUpdate_Call) Run(run func(update campaign.CampaignUpdate)) *MockRepository_CreateUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(campaign.CampaignUpdate))
	})
	return _c
}

func (_c *MockRepository_CreateUpdate_Call) Return(_a0 campaign.CampaignUpdate, _a1 error) *MockRepository_CreateUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateUpdate_Call) RunAndReturn(run func(campaign.CampaignUpdate) (campaign.CampaignUpdate, error)) *MockRepository_CreateUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWalletTransaction provides a mock function with given fields: tx, transaction
func (_m *MockRepository) CreateWalletTransaction(tx *gorm.DB, transaction wallet.WalletTransaction) error {
	ret := _m.Called(tx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for CreateWalletTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, wallet.WalletTransaction) error); ok {
		r0 = rf(tx, transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateWalletTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWalletTransaction'
type MockRepository_CreateWalletTransaction_Call struct {
	*mock.Call
}

// CreateWalletTransaction is a helper method to define mock.On call
//   - tx *gorm.DB
//   - transaction wallet.WalletTransaction
func (_e *MockRepository_Expecter) CreateWalletTransaction(tx interface{}, transaction interface{}) *MockRepository_CreateWalletTransaction_Call {
	return &MockRepository_CreateWalletTransaction_Call{Call: _e.mock.On("CreateWalletTransaction", tx, transaction)}
}

func (_c *MockRepository_CreateWalletTransaction_Call) Run(run func(tx *gorm.DB, transaction wallet.WalletTransaction)) *MockRepository_CreateWalletTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(wallet.WalletTransaction))
	})
	return _c
}

func (_c *MockRepository_CreateWalletTransaction_Call) Return(_a0 error) *MockRepository_CreateWalletTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateWalletTransaction_Call) RunAndReturn(run func(*gorm.DB, wallet.WalletTransaction) error) *MockRepository_CreateWalletTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockRepository) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int
func (_e *MockRepository_Expecter) Delete(id interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(id int)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(_a0 error) *MockRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(int) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DonorUserIDs provides a mock function with given fields: campaignID
func (_m *MockRepository) DonorUserIDs(campaignID int) ([]int, error) {
	ret := _m.Called(campaignID)

	if len(ret) == 0 {
		panic("no return value specified for DonorUserIDs")
	}

	var r0 []int
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]int, error)); ok {
		return rf(campaignID)
	}
	if rf, ok := ret.Get(0).(func(int) []int); ok {
		r0 = rf(campaignID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(campaignID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_DonorUserIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DonorUserIDs'
type MockRepository_DonorUserIDs_Call struct {
	*mock.Call
}

// DonorUserIDs is a helper method to define mock.On call
//   - campaignID int
func (_e *MockRepository_Expecter) DonorUserIDs(campaignID interface{}) *MockRepository_DonorUserIDs_Call {
	return &MockRepository_DonorUserIDs_Call{Call: _e.mock.On("DonorUserIDs", campaignID)}
}

func (_c *MockRepository_DonorUserIDs_Call) Run(run func(campaignID int)) *MockRepository_DonorUserIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_DonorUserIDs_Call) Return(_a0 []int, _a1 error) *MockRepository_DonorUserIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_DonorUserIDs_Call) RunAndReturn(run func(int) ([]int, error)) *MockRepository_DonorUserIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindWalletByUserID provides a mock function with given fields: tx, userID
func (_m *MockRepository) FindWalletByUserID(tx *gorm.DB, userID int) (wallet.Wallet, error) {
	ret := _m.Called(tx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindWalletByUserID")
	}

	var r0 wallet.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, int) (wallet.Wallet, error)); ok {
		return rf(tx, userID)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, int) wallet.Wallet); ok {
		r0 = rf(tx, userID)
	} else {
		r0 = ret.Get(0).(wallet.Wallet)
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, int) error); ok {
		r1 = rf(tx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindWalletByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindWalletByUserID'
type MockRepository_FindWalletByUserID_Call struct {
	*mock.Call
}

// FindWalletByUserID is a helper method to define mock.On call
//   - tx *gorm.DB
//   - userID int
func (_e *MockRepository_Expecter) FindWalletByUserID(tx interface{}, userID interface{}) *MockRepository_FindWalletByUserID_Call {
	return &MockRepository_FindWalletByUserID_Call{Call: _e.mock.On("FindWalletByUserID", tx, userID)}
}

func (_c *MockRepository_FindWalletByUserID_Call) Run(run func(tx *gorm.DB, userID int)) *MockRepository_FindWalletByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(int))
	})
	return _c
}

func (_c *MockRepository_FindWalletByUserID_Call) Return(_a0 wallet.Wallet, _a1 error) *MockRepository_FindWalletByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindWalletByUserID_Call) RunAndReturn(run func(*gorm.DB, int) (wallet.Wallet, error)) *MockRepository_FindWalletByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: id
func (_m *MockRepository) Get(id int) (campaign.Campaign, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 campaign.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (campaign.Campaign, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) campaign.Campaign); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(campaign.Campaign)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id int
func (_e *MockRepository_Expecter) Get(id interface{}) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MockRepository_Get_Call) Run(run func(id int)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(_a0 campaign.Campaign, _a1 error) *MockRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(int) (campaign.Campaign, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// IncreaseCampaignAmount provides a mock function with given fields: tx, campaignID, amount
func (_m *MockRepository) IncreaseCampaignAmount(tx *gorm.DB, campaignID int, amount float64) error {
	ret := _m.Called(tx, campaignID, amount)

	if len(ret) == 0 {
		panic("no return value specified for IncreaseCampaignAmount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, int, float64) error); ok {
		r0 = rf(tx, campaignID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_IncreaseCampaignAmount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncreaseCampaignAmount'
type MockRepository_IncreaseCampaignAmount_Call struct {
	*mock.Call
}

// IncreaseCampaignAmount is a helper method to define mock.On call
//   - tx *gorm.DB
//   - campaignID int
//   - amount float64
func (_e *MockRepository_Expecter) IncreaseCampaignAmount(tx interface{}, campaignID interface{}, amount interface{}) *MockRepository_IncreaseCampaignAmount_Call {
	return &MockRepository_IncreaseCampaignAmount_Call{Call: _e.mock.On("IncreaseCampaignAmount", tx, campaignID, amount)}
}

func (_c *MockRepository_IncreaseCampaignAmount_Call) Run(run func(tx *gorm.DB, campaignID int, amount float64)) *MockRepository_IncreaseCampaignAmount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(int), args[2].(float64))
	})
	return _c
}

func (_c *MockRepository_IncreaseCampaignAmount_Call) Return(_a0 error) *MockRepository_IncreaseCampaignAmount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_IncreaseCampaignAmount_Call) RunAndReturn(run func(*gorm.DB, int, float64) error) *MockRepository_IncreaseCampaignAmount_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with no fields
func (_m *MockRepository) List() ([]campaign.Campaign, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []campaign.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]campaign.Campaign, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []campaign.Campaign); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]campaign.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockRepository_Expecter) List() *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockRepository_List_Call) Run(run func()) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(_a0 []campaign.Campaign, _a1 error) *MockRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func() ([]campaign.Campaign, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListUpdate provides a mock function with given fields: campaignID
func (_m *MockRepository) ListUpdate(campaignID int) ([]campaign.CampaignUpdate, error) {
	ret := _m.Called(campaignID)

	if len(ret) == 0 {
		panic("no return value specified for ListUpdate")
	}

	var r0 []campaign.CampaignUpdate
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]campaign.CampaignUpdate, error)); ok {
		return rf(campaignID)
	}
	if rf, ok := ret.Get(0).(func(int) []campaign.CampaignUpdate); ok {
		r0 = rf(campaignID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]campaign.CampaignUpdate)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(campaignID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUpdate'
type MockRepository_ListUpdate_Call struct {
	*mock.Call
}

// ListUpdate is a helper method to define mock.On call
//   - campaignID int
func (_e *MockRepository_Expecter) ListUpdate(campaignID interface{}) *MockRepository_ListUpdate_Call {
	return &MockRepository_ListUpdate_Call{Call: _e.mock.On("ListUpdate", campaignID)}
}

func (_c *MockRepository_ListUpdate_Call) Run(run func(campaignID int)) *MockRepository_ListUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_ListUpdate_Call) Return(_a0 []campaign.CampaignUpdate, _a1 error) *MockRepository_ListUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListUpdate_Call) RunAndReturn(run func(int) ([]campaign.CampaignUpdate, error)) *MockRepository_ListUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// MyDonations provides a mock function with given fields: userID
func (_m *MockRepository) MyDonations(userID int) ([]campaign.Donation, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for MyDonations")
	}

	var r0 []campaign.Donation
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]campaign.Donation, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) []campaign.Donation); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]campaign.Donation)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_MyDonations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MyDonations'
type MockRepository_MyDonations_Call struct {
	*mock.Call
}

// MyDonations is a helper method to define mock.On call
//   - userID int
func (_e *MockRepository_Expecter) MyDonations(userID interface{}) *MockRepository_MyDonations_Call {
	return &MockRepository_MyDonations_Call{Call: _e.mock.On("MyDonations", userID)}
}

func (_c *MockRepository_MyDonations_Call) Run(run func(userID int)) *MockRepository_MyDonations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_MyDonations_Call) Return(_a0 []campaign.Donation, _a1 error) *MockRepository_MyDonations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_MyDonations_Call) RunAndReturn(run func(int) ([]campaign.Donation, error)) *MockRepository_MyDonations_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: c
func (_m *MockRepository) Update(c campaign.Campaign) (campaign.Campaign, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 campaign.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(campaign.Campaign) (campaign.Campaign, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(campaign.Campaign) campaign.Campaign); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(campaign.Campaign)
	}

	if rf, ok := ret.Get(1).(func(campaign.Campaign) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - c campaign.Campaign
func (_e *MockRepository_Expecter) Update(c interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", c)}
}

func (_c *MockRepository_Update_Call) Run(run func(c campaign.Campaign)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(campaign.Campaign))
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(_a0 campaign.Campaign, _a1 error) *MockRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(campaign.Campaign) (campaign.Campaign, error)) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWallet provides a mock function with given fields: tx, _a1
func (_m *MockRepository) UpdateWallet(tx *gorm.DB, _a1 wallet.Wallet) error {
	ret := _m.Called(tx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWallet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, wallet.Wallet) error); ok {
		r0 = rf(tx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWallet'
type MockRepository_UpdateWallet_Call struct {
	*mock.Call
}

// UpdateWallet is a helper method to define mock.On call
//   - tx *gorm.DB
//   - _a1 wallet.Wallet
func (_e *MockRepository_Expecter) UpdateWallet(tx interface{}, _a1 interface{}) *MockRepository_UpdateWallet_Call {
	return &MockRepository_UpdateWallet_Call{Call: _e.mock.On("UpdateWallet", tx, _a1)}
}

func (_c *MockRepository_UpdateWallet_Call) Run(run func(tx *gorm.DB, _a1 wallet.Wallet)) *MockRepository_UpdateWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(wallet.Wallet))
	})
	return _c
}

func (_c *MockRepository_UpdateWallet_Call) Return(_a0 error) *MockRepository_UpdateWallet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateWallet_Call) RunAndReturn(run func(*gorm.DB, wallet.Wallet) error) *MockRepository_UpdateWallet_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
