// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	campaign "github.com/fahmi0sd/waste-banks-and-donations/service/campaign"
	mock "github.com/stretchr/testify/mock"
)

// MockUpdateRepository is an autogenerated mock type for the UpdateRepository type
type MockUpdateRepository struct {
	mock.Mock
}

type MockUpdateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateRepository) EXPECT() *MockUpdateRepository_Expecter {
	return &MockUpdateRepository_Expecter{mock: &_m.Mock}
}

// CreateUpdate provides a mock function with given fields: update
func (_m *MockUpdateRepository) CreateUpdate(update campaign.CampaignUpdate) (campaign.CampaignUpdate, error) {
	ret := _m.Called(update)

	if len(ret) == 0 {
		panic("no return value specified for CreateUpdate")
	}

	var r0 campaign.CampaignUpdate
	var r1 error
	if rf, ok := ret.Get(0).(func(campaign.CampaignUpdate) (campaign.CampaignUpdate, error)); ok {
		return rf(update)
	}
	if rf, ok := ret.Get(0).(func(campaign.CampaignUpdate) campaign.CampaignUpdate); ok {
		r0 = rf(update)
	} else {
		r0 = ret.Get(0).(campaign.CampaignUpdate)
	}

	if rf, ok := ret.Get(1).(func(campaign.CampaignUpdate) error); ok {
		r1 = rf(update)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateRepository_CreateUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUpdate'
type MockUpdateRepository_CreateUpdate_Call struct {
	*mock.Call
}

// CreateUpdate is a helper method to define mock.On call
//   - update campaign.CampaignUpdate
func (_e *MockUpdateRepository_Expecter) CreateUpdate(update interface{}) *MockUpdateRepository_CreateUpdate_Call {
	return &MockUpdateRepository_CreateUpdate_Call{Call: _e.mock.On("CreateUpdate", update)}
}

func (_c *MockUpdateRepository_CreateUpdate_Call) Run(run func(update campaign.CampaignUpdate)) *MockUpdateRepository_CreateUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(campaign.CampaignUpdate))
	})
	return _c
}

func (_c *MockUpdateRepository_CreateUpdate_Call) Return(_a0 campaign.CampaignUpdate, _a1 error) *MockUpdateRepository_CreateUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateRepository_CreateUpdate_Call) RunAndReturn(run func(campaign.CampaignUpdate) (campaign.CampaignUpdate, error)) *MockUpdateRepository_CreateUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// ListUpdate provides a mock function with given fields: campaignID
func (_m *MockUpdateRepository) ListUpdate(campaignID int) ([]campaign.CampaignUpdate, error) {
	ret := _m.Called(campaignID)

	if len(ret) == 0 {
		panic("no return value specified for ListUpdate")
	}

	var r0 []campaign.CampaignUpdate
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]campaign.CampaignUpdate, error)); ok {
		return rf(campaignID)
	}
	if rf, ok := ret.Get(0).(func(int) []campaign.CampaignUpdate); ok {
		r0 = rf(campaignID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]campaign.CampaignUpdate)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(campaignID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateRepository_ListUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUpdate'
type MockUpdateRepository_ListUpdate_Call struct {
	*mock.Call
}

// ListUpdate is a helper method to define mock.On call
//   - campaignID int
func (_e *MockUpdateRepository_Expecter) ListUpdate(campaignID interface{}) *MockUpdateRepository_ListUpdate_Call {
	return &MockUpdateRepository_ListUpdate_Call{Call: _e.mock.On("ListUpdate", campaignID)}
}

func (_c *MockUpdateRepository_ListUpdate_Call) Run(run func(campaignID int)) *MockUpdateRepository_ListUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockUpdateRepository_ListUpdate_Call) Return(_a0 []campaign.CampaignUpdate, _a1 error) *MockUpdateRepository_ListUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateRepository_ListUpdate_Call) RunAndReturn(run func(int) ([]campaign.CampaignUpdate, error)) *MockUpdateRepository_ListUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateRepository creates a new instance of MockUpdateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateRepository {
	mock := &MockUpdateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
