// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	queue "github.com/fahmi0sd/waste-banks-and-donations/service/queue"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AdminLocation provides a mock function with given fields: userID
func (_m *MockRepository) AdminLocation(userID int) (string, *int, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for AdminLocation")
	}

	var r0 string
	var r1 *int
	var r2 error
	if rf, ok := ret.Get(0).(func(int) (string, *int, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int) *int); ok {
		r1 = rf(userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*int)
		}
	}

	if rf, ok := ret.Get(2).(func(int) error); ok {
		r2 = rf(userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_AdminLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminLocation'
type MockRepository_AdminLocation_Call struct {
	*mock.Call
}

// AdminLocation is a helper method to define mock.On call
//   - userID int
func (_e *MockRepository_Expecter) AdminLocation(userID interface{}) *MockRepository_AdminLocation_Call {
	return &MockRepository_AdminLocation_Call{Call: _e.mock.On("AdminLocation", userID)}
}

func (_c *MockRepository_AdminLocation_Call) Run(run func(userID int)) *MockRepository_AdminLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_AdminLocation_Call) Return(role string, locationID *int, err error) *MockRepository_AdminLocation_Call {
	_c.Call.Return(role, locationID, err)
	return _c
}

func (_c *MockRepository_AdminLocation_Call) RunAndReturn(run func(int) (string, *int, error)) *MockRepository_AdminLocation_Call {
	_c.Call.Return(run)
	return _c
}

// CountTodayByLocation provides a mock function with given fields: locationID
func (_m *MockRepository) CountTodayByLocation(locationID int) (int, error) {
	ret := _m.Called(locationID)

	if len(ret) == 0 {
		panic("no return value specified for CountTodayByLocation")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (int, error)); ok {
		return rf(locationID)
	}
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(locationID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(locationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CountTodayByLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountTodayByLocation'
type MockRepository_CountTodayByLocation_Call struct {
	*mock.Call
}

// CountTodayByLocation is a helper method to define mock.On call
//   - locationID int
func (_e *MockRepository_Expecter) CountTodayByLocation(locationID interface{}) *MockRepository_CountTodayByLocation_Call {
	return &MockRepository_CountTodayByLocation_Call{Call: _e.mock.On("CountTodayByLocation", locationID)}
}

func (_c *MockRepository_CountTodayByLocation_Call) Run(run func(locationID int)) *MockRepository_CountTodayByLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_CountTodayByLocation_Call) Return(_a0 int, _a1 error) *MockRepository_CountTodayByLocation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CountTodayByLocation_Call) RunAndReturn(run func(int) (int, error)) *MockRepository_CountTodayByLocation_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: q
func (_m *MockRepository) Create(q queue.Queue) (queue.Queue, error) {
	ret := _m.Called(q)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 queue.Queue
	var r1 error
	if rf, ok := ret.Get(0).(func(queue.Queue) (queue.Queue, error)); ok {
		return rf(q)
	}
	if rf, ok := ret.Get(0).(func(queue.Queue) queue.Queue); ok {
		r0 = rf(q)
	} else {
		r0 = ret.Get(0).(queue.Queue)
	}

	if rf, ok := ret.Get(1).(func(queue.Queue) error); ok {
		r1 = rf(q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - q queue.Queue
func (_e *MockRepository_Expecter) Create(q interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", q)}
}

func (_c *MockRepository_Create_Call) Run(run func(q queue.Queue)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(queue.Queue))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 queue.Queue, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(queue.Queue) (queue.Queue, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockRepository) GetByID(id int) (queue.Queue, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 queue.Queue
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (queue.Queue, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) queue.Queue); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(queue.Queue)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int
func (_e *MockRepository_Expecter) GetByID(id interface{}) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(id int)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(_a0 queue.Queue, _a1 error) *MockRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(int) (queue.Queue, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListWaitingByLocation provides a mock function with given fields: locationID
func (_m *MockRepository) ListWaitingByLocation(locationID int) ([]queue.QueueWithUser, error) {
	ret := _m.Called(locationID)

	if len(ret) == 0 {
		panic("no return value specified for ListWaitingByLocation")
	}

	var r0 []queue.QueueWithUser
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]queue.QueueWithUser, error)); ok {
		return rf(locationID)
	}
	if rf, ok := ret.Get(0).(func(int) []queue.QueueWithUser); ok {
		r0 = rf(locationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queue.QueueWithUser)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(locationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListWaitingByLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWaitingByLocation'
type MockRepository_ListWaitingByLocation_Call struct {
	*mock.Call
}

// ListWaitingByLocation is a helper method to define mock.On call
//   - locationID int
func (_e *MockRepository_Expecter) ListWaitingByLocation(locationID interface{}) *MockRepository_ListWaitingByLocation_Call {
	return &MockRepository_ListWaitingByLocation_Call{Call: _e.mock.On("ListWaitingByLocation", locationID)}
}

func (_c *MockRepository_ListWaitingByLocation_Call) Run(run func(locationID int)) *MockRepository_ListWaitingByLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_ListWaitingByLocation_Call) Return(_a0 []queue.QueueWithUser, _a1 error) *MockRepository_ListWaitingByLocation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListWaitingByLocation_Call) RunAndReturn(run func(int) ([]queue.QueueWithUser, error)) *MockRepository_ListWaitingByLocation_Call {
	_c.Call.Return(run)
	return _c
}

// LocationInfo provides a mock function with given fields: locationID
func (_m *MockRepository) LocationInfo(locationID int) (bool, bool, string, string, error) {
	ret := _m.Called(locationID)

	if len(ret) == 0 {
		panic("no return value specified for LocationInfo")
	}

	var r0 bool
	var r1 bool
	var r2 string
	var r3 string
	var r4 error
	if rf, ok := ret.Get(0).(func(int) (bool, bool, string, string, error)); ok {
		return rf(locationID)
	}
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(locationID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int) bool); ok {
		r1 = rf(locationID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(int) string); ok {
		r2 = rf(locationID)
	} else {
		r2 = ret.Get(2).(string)
	}

	if rf, ok := ret.Get(3).(func(int) string); ok {
		r3 = rf(locationID)
	} else {
		r3 = ret.Get(3).(string)
	}

	if rf, ok := ret.Get(4).(func(int) error); ok {
		r4 = rf(locationID)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// MockRepository_LocationInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LocationInfo'
type MockRepository_LocationInfo_Call struct {
	*mock.Call
}

// LocationInfo is a helper method to define mock.On call
//   - locationID int
func (_e *MockRepository_Expecter) LocationInfo(locationID interface{}) *MockRepository_LocationInfo_Call {
	return &MockRepository_LocationInfo_Call{Call: _e.mock.On("LocationInfo", locationID)}
}

func (_c *MockRepository_LocationInfo_Call) Run(run func(locationID int)) *MockRepository_LocationInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_LocationInfo_Call) Return(exists bool, isOpen bool, openTime string, closeTime string, err error) *MockRepository_LocationInfo_Call {
	_c.Call.Return(exists, isOpen, openTime, closeTime, err)
	return _c
}

func (_c *MockRepository_LocationInfo_Call) RunAndReturn(run func(int) (bool, bool, string, string, error)) *MockRepository_LocationInfo_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: id, status, verifiedBy
func (_m *MockRepository) UpdateStatus(id int, status string, verifiedBy int) error {
	ret := _m.Called(id, status, verifiedBy)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string, int) error); ok {
		r0 = rf(id, status, verifiedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - id int
//   - status string
//   - verifiedBy int
func (_e *MockRepository_Expecter) UpdateStatus(id interface{}, status interface{}, verifiedBy interface{}) *MockRepository_UpdateStatus_Call {
	return &MockRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", id, status, verifiedBy)}
}

func (_c *MockRepository_UpdateStatus_Call) Run(run func(id int, status string, verifiedBy int)) *MockRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockRepository_UpdateStatus_Call) Return(_a0 error) *MockRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateStatus_Call) RunAndReturn(run func(int, string, int) error) *MockRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
