// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	wallet "github.com/fahmi0sd/waste-banks-and-donations/service/wallet"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetTransactions provides a mock function with given fields: userID
func (_m *MockRepository) GetTransactions(userID int) ([]wallet.WalletTransaction, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactions")
	}

	var r0 []wallet.WalletTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]wallet.WalletTransaction, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) []wallet.WalletTransaction); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]wallet.WalletTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactions'
type MockRepository_GetTransactions_Call struct {
	*mock.Call
}

// GetTransactions is a helper method to define mock.On call
//   - userID int
func (_e *MockRepository_Expecter) GetTransactions(userID interface{}) *MockRepository_GetTransactions_Call {
	return &MockRepository_GetTransactions_Call{Call: _e.mock.On("GetTransactions", userID)}
}

func (_c *MockRepository_GetTransactions_Call) Run(run func(userID int)) *MockRepository_GetTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_GetTransactions_Call) Return(_a0 []wallet.WalletTransaction, _a1 error) *MockRepository_GetTransactions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetTransactions_Call) RunAndReturn(run func(int) ([]wallet.WalletTransaction, error)) *MockRepository_GetTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// GetWallet provides a mock function with given fields: userID
func (_m *MockRepository) GetWallet(userID int) (wallet.Wallet, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWallet")
	}

	var r0 wallet.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (wallet.Wallet, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) wallet.Wallet); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(wallet.Wallet)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWallet'
type MockRepository_GetWallet_Call struct {
	*mock.Call
}

// GetWallet is a helper method to define mock.On call
//   - userID int
func (_e *MockRepository_Expecter) GetWallet(userID interface{}) *MockRepository_GetWallet_Call {
	return &MockRepository_GetWallet_Call{Call: _e.mock.On("GetWallet", userID)}
}

func (_c *MockRepository_GetWallet_Call) Run(run func(userID int)) *MockRepository_GetWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_GetWallet_Call) Return(_a0 wallet.Wallet, _a1 error) *MockRepository_GetWallet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetWallet_Call) RunAndReturn(run func(int) (wallet.Wallet, error)) *MockRepository_GetWallet_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function with given fields: userID, amount
func (_m *MockRepository) Withdraw(userID int, amount float64) (wallet.WalletTransaction, error) {
	ret := _m.Called(userID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 wallet.WalletTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(int, float64) (wallet.WalletTransaction, error)); ok {
		return rf(userID, amount)
	}
	if rf, ok := ret.Get(0).(func(int, float64) wallet.WalletTransaction); ok {
		r0 = rf(userID, amount)
	} else {
		r0 = ret.Get(0).(wallet.WalletTransaction)
	}

	if rf, ok := ret.Get(1).(func(int, float64) error); ok {
		r1 = rf(userID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type MockRepository_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - userID int
//   - amount float64
func (_e *MockRepository_Expecter) Withdraw(userID interface{}, amount interface{}) *MockRepository_Withdraw_Call {
	return &MockRepository_Withdraw_Call{Call: _e.mock.On("Withdraw", userID, amount)}
}

func (_c *MockRepository_Withdraw_Call) Run(run func(userID int, amount float64)) *MockRepository_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(float64))
	})
	return _c
}

func (_c *MockRepository_Withdraw_Call) Return(_a0 wallet.WalletTransaction, _a1 error) *MockRepository_Withdraw_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Withdraw_Call) RunAndReturn(run func(int, float64) (wallet.WalletTransaction, error)) *MockRepository_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
