// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	location "github.com/fahmi0sd/waste-banks-and-donations/service/location"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: l
func (_m *MockRepository) Create(l location.Location) (location.Location, error) {
	ret := _m.Called(l)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 location.Location
	var r1 error
	if rf, ok := ret.Get(0).(func(location.Location) (location.Location, error)); ok {
		return rf(l)
	}
	if rf, ok := ret.Get(0).(func(location.Location) location.Location); ok {
		r0 = rf(l)
	} else {
		r0 = ret.Get(0).(location.Location)
	}

	if rf, ok := ret.Get(1).(func(location.Location) error); ok {
		r1 = rf(l)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - l location.Location
func (_e *MockRepository_Expecter) Create(l interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", l)}
}

func (_c *MockRepository_Create_Call) Run(run func(l location.Location)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(location.Location))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 location.Location, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(location.Location) (location.Location, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockRepository) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int
func (_e *MockRepository_Expecter) Delete(id interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(id int)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(_a0 error) *MockRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(int) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockRepository) GetByID(id int) (location.Location, bool, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 location.Location
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(int) (location.Location, bool, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) location.Location); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(location.Location)
	}

	if rf, ok := ret.Get(1).(func(int) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(int) error); ok {
		r2 = rf(id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int
func (_e *MockRepository_Expecter) GetByID(id interface{}) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(id int)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(_a0 location.Location, _a1 bool, _a2 error) *MockRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(int) (location.Location, bool, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with no fields
func (_m *MockRepository) List() ([]location.Location, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []location.Location
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]location.Location, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []location.Location); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]location.Location)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockRepository_Expecter) List() *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockRepository_List_Call) Run(run func()) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(_a0 []location.Location, _a1 error) *MockRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func() ([]location.Location, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// RoleAndLocation provides a mock function with given fields: userID
func (_m *MockRepository) RoleAndLocation(userID int) (string, *int, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for RoleAndLocation")
	}

	var r0 string
	var r1 *int
	var r2 error
	if rf, ok := ret.Get(0).(func(int) (string, *int, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int) *int); ok {
		r1 = rf(userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*int)
		}
	}

	if rf, ok := ret.Get(2).(func(int) error); ok {
		r2 = rf(userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_RoleAndLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RoleAndLocation'
type MockRepository_RoleAndLocation_Call struct {
	*mock.Call
}

// RoleAndLocation is a helper method to define mock.On call
//   - userID int
func (_e *MockRepository_Expecter) RoleAndLocation(userID interface{}) *MockRepository_RoleAndLocation_Call {
	return &MockRepository_RoleAndLocation_Call{Call: _e.mock.On("RoleAndLocation", userID)}
}

func (_c *MockRepository_RoleAndLocation_Call) Run(run func(userID int)) *MockRepository_RoleAndLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepository_RoleAndLocation_Call) Return(role string, locationID *int, err error) *MockRepository_RoleAndLocation_Call {
	_c.Call.Return(role, locationID, err)
	return _c
}

func (_c *MockRepository_RoleAndLocation_Call) RunAndReturn(run func(int) (string, *int, error)) *MockRepository_RoleAndLocation_Call {
	_c.Call.Return(run)
	return _c
}

// SetOpen provides a mock function with given fields: id, isOpen
func (_m *MockRepository) SetOpen(id int, isOpen bool) error {
	ret := _m.Called(id, isOpen)

	if len(ret) == 0 {
		panic("no return value specified for SetOpen")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, bool) error); ok {
		r0 = rf(id, isOpen)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SetOpen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOpen'
type MockRepository_SetOpen_Call struct {
	*mock.Call
}

// SetOpen is a helper method to define mock.On call
//   - id int
//   - isOpen bool
func (_e *MockRepository_Expecter) SetOpen(id interface{}, isOpen interface{}) *MockRepository_SetOpen_Call {
	return &MockRepository_SetOpen_Call{Call: _e.mock.On("SetOpen", id, isOpen)}
}

func (_c *MockRepository_SetOpen_Call) Run(run func(id int, isOpen bool)) *MockRepository_SetOpen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(bool))
	})
	return _c
}

func (_c *MockRepository_SetOpen_Call) Return(_a0 error) *MockRepository_SetOpen_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SetOpen_Call) RunAndReturn(run func(int, bool) error) *MockRepository_SetOpen_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: id, name, address, latitude, longitude, openTime, closeTime, isOpen
func (_m *MockRepository) Update(id int, name *string, address *string, latitude *float64, longitude *float64, openTime *string, closeTime *string, isOpen *bool) error {
	ret := _m.Called(id, name, address, latitude, longitude, openTime, closeTime, isOpen)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, *string, *string, *float64, *float64, *string, *string, *bool) error); ok {
		r0 = rf(id, name, address, latitude, longitude, openTime, closeTime, isOpen)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id int
//   - name *string
//   - address *string
//   - latitude *float64
//   - longitude *float64
//   - openTime *string
//   - closeTime *string
//   - isOpen *bool
func (_e *MockRepository_Expecter) Update(id interface{}, name interface{}, address interface{}, latitude interface{}, longitude interface{}, openTime interface{}, closeTime interface{}, isOpen interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", id, name, address, latitude, longitude, openTime, closeTime, isOpen)}
}

func (_c *MockRepository_Update_Call) Run(run func(id int, name *string, address *string, latitude *float64, longitude *float64, openTime *string, closeTime *string, isOpen *bool)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(*string), args[2].(*string), args[3].(*float64), args[4].(*float64), args[5].(*string), args[6].(*string), args[7].(*bool))
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(_a0 error) *MockRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(int, *string, *string, *float64, *float64, *string, *string, *bool) error) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
